services:
  - type: web
    name: scm-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://final-machinery.onrender.com/api
